<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
function responder(int $status, array $body): void { http_response_code($status); echo json_encode($body, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); exit; }
$configPath=__DIR__.'/config.php'; if(!is_file($configPath)) responder(503,['error'=>'No disponible.']); $config=require $configPath;
$origin=$_SERVER['HTTP_ORIGIN']??''; if($origin!==($config['site_origin']??'')) responder(403,['error'=>'Origen no autorizado.']); header('Access-Control-Allow-Origin: '.$config['site_origin']);
$paymentId=(string)($_GET['payment_id']??''); if(!preg_match('/^\d{4,30}$/',$paymentId)) responder(422,['error'=>'Pago no válido.']);
$curl=curl_init('https://api.mercadopago.com/v1/payments/'.rawurlencode($paymentId)); curl_setopt_array($curl,[CURLOPT_HTTPHEADER=>['Authorization: Bearer '.($config['access_token']??'')],CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>12]); $response=curl_exec($curl); $httpStatus=(int)curl_getinfo($curl,CURLINFO_HTTP_CODE); curl_close($curl); $payment=json_decode((string)$response,true);
if($httpStatus!==200||!is_array($payment)) responder(404,['error'=>'Pago no encontrado.']); if(($payment['status']??'')!=='approved') responder(200,['status'=>(string)($payment['status']??'')]);
$orderId=(string)($payment['external_reference']??''); if(!preg_match('/^CN-\d{8}-[A-F0-9]{6}$/',$orderId)) responder(409,['error'=>'Referencia de pedido no válida.']);
$ordersPath=__DIR__.'/data/pedidos.json'; $handle=fopen($ordersPath,'c+'); if(!$handle||!flock($handle,LOCK_EX)) responder(500,['error'=>'No se pudo verificar el pedido.']); rewind($handle); $orders=json_decode((string)stream_get_contents($handle),true); $matchedOrder=null;
if(is_array($orders['pedidos']??null)){foreach($orders['pedidos'] as &$order){if(($order['id']??'')!==$orderId)continue;if(abs((float)($order['total']??0)-(float)($payment['transaction_amount']??-1))>0.01)break;$order['pago_confirmado']=true;$order['pago']=['id'=>(string)($payment['id']??$paymentId),'estado'=>'approved','monto'=>(float)$payment['transaction_amount'],'actualizado_en'=>date('c')];$order['actualizado_en']=date('c');$matchedOrder=$order;break;}unset($order);}
if(!$matchedOrder){flock($handle,LOCK_UN);fclose($handle);responder(409,['error'=>'El pago no coincide con el pedido.']);}
$json=json_encode($orders,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); if($json===false||!ftruncate($handle,0)||!rewind($handle)||fwrite($handle,$json)===false||!fflush($handle)){flock($handle,LOCK_UN);fclose($handle);responder(500,['error'=>'No se pudo actualizar el pago.']);} flock($handle,LOCK_UN);fclose($handle);
$items=[]; foreach(($matchedOrder['items']??[]) as $line){$itemId=(string)($line['id']??'');$itemName=(string)($line['nombre']??'');$price=(float)($line['precio']??0);$quantity=(int)($line['cantidad']??0);if($itemId!==''&&$itemName!==''&&$price>0&&$quantity>0)$items[]=['item_id'=>$itemId,'item_name'=>$itemName,'price'=>$price,'quantity'=>$quantity];} if(!$items)responder(500,['error'=>'El pedido confirmado no tiene productos medibles.']);
register_shutdown_function(static function()use($payment):void{try{ignore_user_abort(true);if(function_exists('fastcgi_finish_request'))fastcgi_finish_request();elseif(function_exists('litespeed_finish_request'))litespeed_finish_request();$confirmationPath=dirname(__DIR__).'/admin/confirmation-delivery.php';if(is_file($confirmationPath)){require_once $confirmationPath;if(function_exists('cn_delivery_notify'))cn_delivery_notify($payment);}}catch(Throwable $error){error_log('Casa Natural: confirmation hook requires review.');}});
responder(200,['status'=>'approved','transaction_id'=>(string)($payment['id']??$paymentId),'order_id'=>$orderId,'currency'=>'ARS','value'=>(float)($matchedOrder['subtotal_productos']??0),'shipping'=>(float)($matchedOrder['costo_envio']??0),'transaction_amount'=>(float)$payment['transaction_amount'],'items'=>$items]);
